### ISSUE TITLE
Function call order

### ISSUE THREAD

**Issue by Howld** [eXpl0it3r/SmallGameEngine#5]
Link: https://github.com/eXpl0it3r/SmallGameEngine/blob/master/src/Application.cpp#L5

This function should be called after window created.
<pre>
m_window.setFramerateLimit( 30 );
</pre>

**Comment by eXpl0it3r** [comment]
Nice catch. Guess I've been so used to having my window initialized in the initialization list, as I generally do, that I forgot to really do it right here.

**Comment by eXpl0it3r** [comment]
Fixed with 2fa8f5f6eb0eb95e63f25a23b9e034975e1e2e12
